routes/web.php
<?php

Auth::routes();
Route::get('/',function (){
    return Redirect::to('/login');
});
//Route::get('/', 'HomeController@index');


Route::group(['middleware' => ['auth']], function () {

    Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    Route::prefix('roles')->group(function () {
        Route::resource('/menu', 'Roles\MenuController');
        Route::get('/menu/menuControllerChangeStatus/{id}', 'Roles\MenuController@changeStatus');
        Route::resource('/group', 'Roles\UserGroupController');
        Route::get('/roleAccessIndex', 'Roles\RoleAccessController@index');
        Route::get('roleChangeAccess/{allowId}/{id}', 'Roles\RoleAccessController@changeAccess');
    });

    Route::resource('/user', 'UserController');
    Route::get('/user/status/{id}', 'UserController@status');
    Route::get('/profile', 'UserController@profile')->name('profile');
    Route::post('profile/profilePic', 'UserController@profilePic');
    Route::post('/profile/password', 'UserController@password');

    Route::prefix('configurations')->group(function () {
        Route::resource('/designation', 'Configurations\DesignationController');
        Route::resource('/department', 'Configurations\DepartmentController');
        Route::resource('/fiscalYear', 'Configurations\FiscalYearController');
        Route::get('/fiscalYear/status/{id}', 'Configurations\FiscalYearController@status');
        Route::resource('/country', 'Configurations\CountryController');
        Route::get('/country/status/{id}', 'Configurations\CountryController@status');
        Route::resource('/pradesh', 'Configurations\PradeshController');
        Route::resource('/muniType', 'Configurations\MuniTypeController');
        Route::resource('/district', 'Configurations\DistrictController');
        Route::resource('/municipality', 'Configurations\MunicipalityController');
        Route::resource('/officeType', 'Configurations\OfficeTypeController');

        Route::resource('/office', 'Configurations\OfficeController');
        Route::get('/office/status/{id}', 'Configurations\OfficeController@status');


    });

    Route::prefix('logs')->group(function () {
        Route::get('/loginLogs', 'LogController@loginLogs');
        Route::get('/failLoginLogs', 'LogController@failLogin');
    });

    Route::resource('feedback','FeedbackController');

});

app/Models/Roles/Menu.php
<?php

namespace App\Models\Roles;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\SoftDeletes;

class Menu extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $fillable=['parent_id','menu_name','menu_controller','menu_link','menu_css',
        'menu_icon','menu_status','menu_order'];

    public $timestamps = false;

    public static function getMenu($id)
    {

        if (Auth::user()->user_group_id == 1) {
            $result = DB::table('menus')
                ->where('parent_id', $id)->where('menu_status', 1)
                ->orderBy('menu_order', 'ASC')
                ->get();
        } else {
            $result = DB::table('menus')->select('menus.*')
                ->join('user_roles', 'menus.id', '=', 'user_roles.menu_id')
                ->where('parent_id', $id)
                ->where('menu_status', 1)
                ->where('allow_view', 1)
                ->where('user_group_id', Auth::user()->user_group_id)
                ->orderBy('menu_order', 'ASC')
                ->get();
        }
        return $result;

    }
    public static function getMenus()
    {
        /* return DB::table('menus')
             ->select('menus.*')
             ->get();
        */

        return $result = DB::table('menus')->select('menus.*')
            ->join('user_roles', 'menus.id', '=', 'user_roles.menu_id')
            ->where('parent_id', 0)
            ->where('menu_status', 1)
            ->where('allow_view', 1)
            ->where('user_group_id', Auth::user()->user_group_id)
            ->orderBy('menu_order', 'ASC')
            ->get();
    }
}

app/Models/Roles/UserGroup.php
<?php

namespace App\Models\Roles;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class UserGroup extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $fillable=['group_name','group_details'];
    public function users(){
        return $this->hasMany('App\User');
    }
    public function user_roles(){
        return $this->hasMany('App\Models\Configurations\UserRole');
    }
}

app/Models/Roles/UserRole.php
<?php

namespace App\Models\Roles;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class UserRole extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $fillable=['user_group_id','menu_id','allow_view','allow_add','allow_edit','allow_delete',];

    public function user_group(){
        return $this->belongsTo('App\Models\Configurations\UserGroup','user_group_id','id');
    }
}

app/Http/Controllers/Roles/MenuController.php
<?php

namespace App\Http\Controllers\Roles;

use App\Http\Controllers\BaseController;
use App\Http\Requests\Roles\MenuRequest;
use App\Models\Roles\Menu;
use App\Repository\Roles\MenuRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class MenuController extends BaseController
{

    /**
     * @var MenuRepository
     */
    private $menuRepository;

    public function __construct(MenuRepository $menuRepository)
    {
        parent::__construct();
        $this->menuRepository = $menuRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $menus=$this->menuRepository->all();
        $parentList=$this->menuRepository->parentList();
        return view('backend.roles.menus.index',compact('menus','parentList'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(MenuRequest $request)
    {
        try{
            if($request['parent_id'] == null){
                $request['parent_id'] = 0;
            }
            $create=Menu::create($request->all());
            if($create){
                session()->flash('success','Menu successfully created');
                return back();
            }else{
                session()->flash('error','Menu could not be created');
                return back();
            }
        }catch (\Exception $e){
            $e = $e->getMessage();
            session()->flash('error','Exception : '.$e);
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try{
            $id=(int)$id;
            $edits=$this->menuRepository->findById($id);
            if(!empty($edits)){
                $parentList=$this->menuRepository->parentList();
                $parentList[0]['id']=0;
                $parentList[0]['menu_name']='Parent';
                $menus=$this->menuRepository->all();

                return view('backend.roles.menus.index',compact('menus','parentList','edits'));
            }else{
                session()->flash('error','Id could not be obtained');
                return back();
            }

        }catch (\Exception $e){
            $exception=$e->getMessage();
            session()->flash('error','EXCEPTION :'.$exception);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(MenuRequest $request, $id)
    {
        $id=(int)$id;
        try{
            $menu=$this->menuRepository->findById($id);
            if($menu){
                $menu->fill($request->all())->save();
                session()->flash('success','Menu updated successfully');

                return redirect(route('menu.index'));
            }else{

                session()->flash('error','No record with given id');
                return back();
            }
        }catch (\Exception $e){
            $exception=$e->getMessage();
            session()->flash('error','EXCEPTION:'.$exception);
            return back();
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $id=(int)$id;
        try{
            $menu = Menu::find($id);
            $roles = DB::table('user_roles')->where('menu_id',$menu->id)->select('id')->get();
            $menus = DB::table('menus')->where('parent_id',$menu->id)->select('id')->get();

            if(count($roles) == '' && count($menus) == '')
            {
                if($menu->destroy($id)){
                    session()->flash('success','Menu successfully deleted');
                    return back();
                }else{
                    session()->flash('error','Menu could not be deleted');
                    return back();
                }
            }
            session()->flash('warning','Unable to delete');
            return back();

        }catch (\Exception $e){
            $exception=$e->getMessage();
            session()->flash('error','EXCEPTION'.$exception);
            return back();

        }
    }

    public function changeStatus($id){

        try{
            $id=(int)$id;
            $menu=$this->menuRepository->findById($id);
            if($menu->menu_status =='0'){
                $menu->menu_status='1';
                $menu->save();
                session()->flash('success','Menu Successfully Activated');
                return back();
            }
            $menu->menu_status='0';
            $menu->save();
            session()->flash('success','Menu Successfully Deactivated');
            return back();
        }catch (\Exception $e){
            $message=$e->getMessage();
            session()->flash('error',$message);
            return back();
        }

    }
}

app/Http/Controllers/Roles/RoleAccessController.php
<?php

namespace App\Http\Controllers\Roles;

use App\Http\Controllers\BaseController;
use App\Models\Roles\UserRole;
use App\Repository\Roles\MenuRepository;
use App\Repository\Roles\UserGroupRepository;
use App\Repository\Roles\UserRolesRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RoleAccessController extends BaseController
{
    /**
     * @var UserGroupRepository
     */
    private $userGroupRepository;
    /**
     * @var MenuRepository
     */
    private $menuRepository;
    /**
     * @var UserRole
     */
    private $userRole;
    /**
     * @var UserRolesRepository
     */
    private $userRolesRepository;

    public function __construct(UserGroupRepository $userGroupRepository,
                                MenuRepository $menuRepository,UserRole $userRole, UserRolesRepository $userRolesRepository)
    {
        parent::__construct();
        $this->userGroupRepository = $userGroupRepository;
        $this->menuRepository = $menuRepository;
        $this->userRole = $userRole;
        $this->userRolesRepository = $userRolesRepository;
    }

    public function index(Request $request)
    {
        $groupList=$this->userGroupRepository->groupList();
        if ($request->has('group_id')) {
            $group_id = $request->get('group_id');
        } else {
            $group_id = 0;
        }

        if ($request->has('group_id')) {
            $menus = $this->menuRepository->getAccessMenu(0, $group_id);
        } else {
            $menus = [];
        }
        $this->userRolesRepository->copyMenu($group_id);
        $menuRepo= $this->menuRepository;
        return view('backend.roles.roleAccess',compact('menus','groupList','menuRepo'));
    }

    public function changeAccess($allowId, $id)
    {
        $this->userRolesRepository->changePermission($allowId, $id);
    }
}

app/Http/Controllers/Roles/UserGroupController.php
<?php

namespace App\Http\Controllers\Roles;

use App\Http\Controllers\BaseController;
use App\Http\Requests\Roles\GroupRequest;
use App\Models\Roles\UserGroup;
use App\Repository\Roles\UserGroupRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class UserGroupController extends BaseController
{
    /**
     * @var UserGroupRepository
     */
    private $userGroupRepository;
    /**
     * @var UserGroup
     */
    private $userGroup;

    public function __construct(UserGroupRepository $userGroupRepository, UserGroup $userGroup)
    {
        parent::__construct();
        $this->userGroupRepository = $userGroupRepository;
        $this->userGroup = $userGroup;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups=$this->userGroupRepository->all();
        return view('backend.roles.groups.index',compact('groups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(GroupRequest $request)
    {
        try{
            $create=$this->userGroup->create($request->all());

            if($create){
                session()->flash('success','Group successfully created');
                return back();
            }else{
                session()->flash('error','Group couldnot be created');
                return back();
            }
        }catch (\Exception $e){
            $e->getMessage();
            session()->flash('error','Exception : '.$e);
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try{
            $id=(int)$id;
            $edits=$this->userGroupRepository->findById($id);

            if(!empty($edits)){
                $groups=$this->userGroupRepository->all();
                return view('backend.roles.groups.index',compact('groups','edits'));
            }else{
                session()->flash('error','Id could not be obtained');
                return back();
            }

        }catch (\Exception $e){
            $exception=$e->getMessage();
            session()->flash('error','EXCEPTION :'.$exception);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(GroupRequest $request, $id)
    {
        $id=(int)$id;
        try{
            $menu=$this->userGroupRepository->findById($id);
            if($menu){
                $menu->fill($request->all())->save();
                session()->flash('success','Group updated successfully');

                return redirect(route('group.index'));
            }else{

                session()->flash('error','No record with given id');
                return back();
            }
        }catch (\Exception $e){
            $exception=$e->getMessage();
            session()->flash('error','EXCEPTION:'.$exception);
            return back();
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $id=(int)$id;
        try{
            $roles = DB::table('users')->where('user_group_id',$id)->select('id')->get();

            if(count($roles) == '') {
                if ($this->userGroup->destroy($id)) {
                    session()->flash('success', 'Group successfully deleted');
                    return back();
                } else {
                    session()->flash('error', 'Group could not be deleted');
                    return back();
                }
            }
            else{
                session()->flash('warning', 'Group could not be deleted');
                return back();
            }
        }catch (\Exception $e){
            $exception=$e->getMessage();
            session()->flash('error','EXCEPTION'.$exception);
            return back();

        }
    }
}

resources/views/backend/roles/groups/add.blade.php
<div class="card card-default">
    <div class="card-header with-border">
        <h3 class="card-title">Edit Menu</h3>

    </div>
    <div class="card-body">

            {!! Form::open(['method'=>'post','url'=>'roles/group']) !!}
            <div class="form-group {{ ($errors->has('group_name'))?'has-error':'' }}">
                <label for="group_name">Name</label>
                {!! Form::text('group_name',null,['class'=>'form-control','placeholder'=>'Enter Group Name']) !!}
                {!! $errors->first('group_name', '<span class="text-danger">:message</span>') !!}
            </div>

            <div class="form-group {{ ($errors->has('group_details'))?'has-error':'' }}">
                <label for="group_details">Details</label>
                {!! Form::textarea('group_details',null,['class'=>'form-control','placeholder'=>'Enter Group Description']) !!}
                {!! $errors->first('group_details', '<span class="text-danger">:message</span>') !!}
            </div>

                       <!-- /.form group -->
            <div class="card-footer">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        {!! Form::close() !!}
    </div>
</div>

resources/views/backend/roles/groups/edit.blade.php
<div class="card card-default">
    <div class="card-header with-border">
        <h3 class="card-title">Edit Group</h3>

    </div>
    <div class="card-body">

    {!! Form::model($edits,['method'=>'PUT','route'=>['group.update',$edits->id]]) !!}

        <div class="form-group {{ ($errors->has('group_name'))?'has-error':'' }}">
            <label for="group_name">Name</label>
            {!! Form::text('group_name',null,['class'=>'form-control','placeholder'=>'Enter Group Name']) !!}
            {!! $errors->first('group_name', '<span class="text-danger">:message</span>') !!}
        </div>

        <div class="form-group {{ ($errors->has('group_details'))?'has-error':'' }}">
            <label for="group_details">Details</label>
            {!! Form::textarea('group_details',null,['class'=>'form-control','placeholder'=>'Enter Menu Controller']) !!}
            {!! $errors->first('group_details', '<span class="text-danger">:message</span>') !!}
        </div>

        <!-- /.form group -->
        <div class="card-footer">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <button type="submit" class="btn btn-primary">Update</button>


            </div>
            <!-- /.card-footer -->

        </div>
        {!! Form::close() !!}


    </div>
    <!-- /.card-body -->
</div>

resources/views/backend/roles/groups/index.blade.php
@extends('backend.layouts.app')
@section('title')
    Group
@endsection
@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        <section class="content-header">

            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Group</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{url('/dashboard')}}">Dashboard</a></li>
                            <li class="breadcrumb-item">Roles</li>
                            <li class="breadcrumb-item active">Groups</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
            @include('backend.message.flash')
            <div class="row">
                @if(helperPermission()['isAdd'])
                    <div class="col-md-9" id="listing">
                        @else
                            <div class="col-md-12" id="listing">
                                @endif
                                <div class="card card-default">
                                    <div class="card-header with-border">
                                        <h3 class="card-title"><i class="fa fa-list"></i> Groups</h3>
                                        <?php

                                        $permission = helperPermission();

                                        $allowEdit = $permission['isEdit'];

                                        $allowDelete = $permission['isDelete'];
                                        $allowAdd = $permission['isAdd'];
                                        ?>
                                        <a href="{{url('roles/group')}}" class="pull-right boxTopButton"
                                           data-toggle="tooltip" title="View All"><i class="fa fa-list fa-2x" style="font-size:20px;"></i></a>
                                        <a href="{{url('roles/group')}}" class="pull-right  boxTopButton"
                                           data-toggle="tooltip" title="Go Back"><i
                                                    class="fa fa-arrow-circle-left fa-2x" style="font-size:20px;"></i></a>
                                    </div>

                                    <div class="card-body">

                                        @if(!count($groups)<=0)
                                            <div class="table-responsive">
                                                <table id="example1" class="table table-hover table-striped  table-bordered table-responsive">
                                                    <thead>
                                                    <tr>
                                                        <th>S.N</th>
                                                        <th>Name</th>
                                                        <th>Details</th>
                                                        <th style="width: 50px" class="text-right">Action</th>
                                                    </tr>
                                                    </thead>

                                                    <tbody>
                                                    <?php
                                                    $i = 1;
                                                    ?>
                                                    @foreach($groups as $group)
                                                        <tr>
                                                            <th scope=row>{{$i++}}</th>
                                                            <td>{{$group->group_name}}</td>
                                                            <td>{{$group->group_details}}</td>

                                                            <td class="text-right row" style="margin-right: 0px;">
                                                                @if($allowEdit)
                                                                    <a href="{{route('group.edit',[$group->id])}}"
                                                                       class="text-info btn btn-xs btn-default"
                                                                       data-toggle="tooltip"
                                                                       data-placement="top" title="Edit" style="margin: 0 5px;">
                                                                        <i class="fa fa-pencil-square-o"></i>
                                                                    </a>
                                                                @endif


                                                                @if($allowDelete)
                                                                    {!! Form::open(['method' => 'DELETE', 'route'=>['group.destroy',$group->id],'class'=>'inline']) !!}

                                                                    <button type="submit"
                                                                            class="btn btn-danger btn-xs deleteButton actionIcon"
                                                                            data-toggle="tooltip"
                                                                            data-placement="top" title="Delete"
                                                                            onclick="javascript:return confirm('Are you sure you want to delete?');">
                                                                        <i class="fa fa-trash"></i>
                                                                    </button>
                                                                @endif

                                                                {!! Form::close() !!}
                                                            </td>
                                                        </tr>
                                                    @endforeach

                                                    </tbody>

                                                </table>
                                            </div>


                                        @else
                                            <div class="col-md-12">
                                                <label class="form-control label-danger">No records found</label>
                                            </div>
                                        @endif

                                    </div>

                                    <!-- /.card-body -->
                                </div>
                                <!-- /.card -->
                            </div>

                            @if($allowAdd)
                                <div class="col-md-3">
                                    @if(\Request::segment(4)=='edit')
                                        @include('backend.roles.groups.edit')
                                    @else
                                        @include('backend.roles.groups.add')
                                    @endif

                                </div>
                            @endif
                    </div>
            </div>
            </div>
        </section>
        <!-- /.content -->
    </div>

    <!-- /.content-wrapper -->

@endsection